# -*- coding: utf-8 -*-
"""CaseStudy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYvAclPLkv1ouq2O9QJr7dCjK-HETzvz
"""

# Import Data Manipulation Library
import numpy as np
import pandas as pd
# import Data Visualization Library
import seaborn as sns
import matplotlib.pyplot as plt
# import FilterWarning Library
# import warnings
# warnings.filterwarnings("ignore")
# # import Data Logging
# import logging    # most important
# logging.basicConfig(level=logging.INFO,
#                     filename= "app.log",
#                     filemode= "w",
#                     format= "%(asctime)s - %(Levelname)s - %(message)s")

# import Data Using Pandas Function

url = "https://raw.githubusercontent.com/chandanc5525/Dataset/refs/heads/main/Data/titanic_train.csv"

data = pd.read_csv(url)
data.sample(frac= 1) # Data Shuffle

print(data.info())

# identify Passanger Class Based on Category
data["Pclass"].value_counts()

# Distribution of Passanger Class Based on Category
data["Pclass"].value_counts().plot(kind = "pie",autopct = "%.2f", explode = [0.01,0.01,0.01],figsize = (5,5))
plt.title("Passanger Class Distribution")
plt.legend(["First Class", "Second Class", "Third Class"])
plt.show()

# Distribution of Passanger Class Based on Category
data["SibSp"].value_counts().plot(kind = "barh")
plt.title("Siblings and Spouse Distribution")
plt.show()

# Distribution of Passanger Class Based on Category
data["Embarked"].value_counts().plot(kind = "pie",autopct = "%.2f", explode = [0.01,0.01,0.01],figsize = (5,5))
plt.title("Passanger Board their journey")
plt.legend(["Southampton","Cherbourg","Queenstown"])
plt.show()

# Dataset belongs to embarked = southampton
Southampton = data [data["Embarked"] == "S" ]
print(Southampton)

Southampton["Survived"].value_counts(),Southampton ["Sex"].value_counts()

Southampton [Southampton["Sex"]== "male"]["Survived"].value_counts()

Southampton [Southampton["Sex"]== "female"]["Survived"].value_counts()

Queenstown = data[data["Embarked"]== "Q"]
print(Queenstown)

Queenstown ["Survived"].value_counts(),Queenstown["Sex"].value_counts()

Queenstown[Queenstown ["Sex"] == "male"]["Survived"].value_counts()

Queenstown [Queenstown ["Sex"] == "female"]["Survived"].value_counts()

Queenstown ["Age"].mean()

survived_people = data[data["Pclass"] == 3]["Survived"]
survived_people.value_counts()



Cherbourg = data[data ["Embarked"] == "C"]
print(Cherbourg)

Cherbourg["Survived"].value_counts(),Cherbourg["Sex"].value_counts()

"""Data Insight :
the given data set contains 12 Columns and 891 Rows out of which column name (Age , Cabin ) having missing value.
the Statigies having decided on above data set.
if column contains more than 5% of missing value then such imputation can be done of median for Age.
For Cabin column we find more values are missing that is the reason we must drop this column for further analysis.

for passangers:
the data set also shows 55.11 passanger belongs to class 3, 20.65 Passangers are belongs to class 2, 24.24 are belongs to class 1.

it was found that southampton 72.44% start their journey.
 8.66% people boarded their journey from Queenstown.
18.90% people boarded their journey from Cherbourg.

in southampton male boarded on ship is 441 and only survived 77 male in that Ship Crashed. and female which are boarded on ship is 203 and only survived 140 Females.



from Queenstown peoples are boarded from are 41 male and 36 female in this only survived are 3 male and 27 female.


from Cherbourg people are boarded 95 male and 73 female and survived people are 29 male and 64 female are survived
"""

Cherbourg[Cherbourg["Sex"]== "male"]["Survived"].value_counts()

Cherbourg[Cherbourg["Sex"]== "female"]["Survived"].value_counts()

crosstab = pd.crosstab(Southampton["Pclass"],Southampton["Survived"])
print(crosstab)

crosstab = pd.crosstab(Queenstown["Pclass"],Queenstown["Survived"])
print(crosstab)

crosstab = pd.crosstab(Cherbourg["Pclass"].value_counts(),Cherbourg["Survived"].value_counts().plot(kind = "pie", autopct =" %.2f"))
print(crosstab)

print(data)

fig,ax = plt.subplots(2,2,figsize = (6,6))
sns.scatterplot(ax=ax[0][0],data=data,x="Parch",y = "Pclass", hue = "Survived")
sns.barplot(ax=ax[0][1],data=data,x="Embarked",y = "Pclass")
sns.pie(ax=ax[1][0],data=data,x="Fare",y = "Pclass")
sns.scatterplot(ax=ax[1][1],data=data,x="Survived",y = "Pclass")
plt.show()







